config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rooms do 
  	member do
  		get :new_booking
  		post :create_booking
      get :edit_booking
      post :update_booking
      delete :destroy_booking
  	end

  	resources :fascilities
  end
  resources :holidays
  #get '/:id' => "shortener/shortened_urls#show"

  root to: "pages#index"
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
	before_action :authenticate_user!

	
	def index
		@holidays = Holiday.where("").order(:created_at).page params[:page]
	end

	def show
		@holiday = Holiday.find(params[:id])
	end

	def new
		@holiday = Holiday.new
	end

	def create
		@holiday = Holiday.new(holiday_params)
		respond_to do |format|
      if @holiday.save
        format.html { redirect_to holidays_path, :flash=> {notice: 'holiday has been created.' }}
        format.json { render :index, status: :created, location: holidays_path }
      else
        format.html { render :index }
        format.json { render json: @holiday, status: :unprocessable_entity }
      end
    end
  end

	def edit
		@holiday = Holiday.find(params[:id])
	end

	def update
		@holiday = Holiday.find(params[:id])
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to holidays_path, :flash=> {notice: 'holiday was successfully updated.' }}
        format.json { render :index, status: :created, location: holidays_path }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@holiday = Holiday.find(params[:id])
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_path, notice: 'holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
	end

private
  def holiday_params
    params.require(:holiday).permit(:title, :holiday_date)
  end

end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.haml
= form_for(@holiday) do |f|
  .row
    .col-sm-4
      .field.form-group
        .control
          = f.label  :title
          = f.text_field :title, class: "input form-control"
      .field.form-group
        = f.label  :holiday_date
        #datetimepicker.input-group.date
          = f.text_field :holiday_date, class: "input form-control"
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
      .field.form-group
        .control
          = f.submit :submit, class: "button is-link btn btn-info"
:javascript
  $(function () {
     var date = $('#datetimepicker').val();
     $('#datetimepicker').datetimepicker({
      format: 'DD/MM/YYYY hh:mm A',
       daysOfWeekDisabled: [0, 6],
       useCurrent: false
       
     });
      
  });

app/views/holidays/edit.html.haml
.section
  .container
    %h1.title.is-2 Editing Holiday
    = render 'form', holiday: @holiday
    = link_to '<--Back', holidays_path, class:'button btn btn-link'

app/views/holidays/index.html.haml
%p#notice= notice
%h1 Holidays
%table.table.table-striped
  %thead
    %tr
      %th Title
      %th Date
      %th.text-center{:colspan => "5"} Action
  %tbody
    - @holidays.each do |holiday|
      %tr
        %td= holiday.title
        %td= holiday.holiday_date
        / <td><haml_silent></haml_silent></td>
        %td= link_to 'Edit', edit_holiday_path(holiday)
        %td= link_to 'Destroy', holiday, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= paginate @holidays, theme: 'my_custom_theme'
%br/
= link_to 'New holidays', new_holiday_path, class: 'btn btn-primary'

app/views/holidays/new.html.haml
.section
  .container
    %h1.title.is-2 New holiday
    = render 'form', holiday: @holiday
    %br/
    = link_to '<--Back', holidays_path, class:'button btn btn-link'

app/views/holidays/show.html.haml
%section.section
  .container
    .columns.is-centered
      .column.is-9
        %h1.title.is-2= @room.room_no
        .level.form-group
          .level-left.control
            %p
              Created on
              \#{@room.created_at} by
              Manager / Modified
              \#{time_ago_in_words(@room.updated_at)}
          .level-left.control
            = link_to 'Edit room', edit_room_path(@room), class:'button'
            = link_to 'Delete room', @room, method: :delete, data: { confirm: 'Are you sure'}, class:'button is-danger is-outlined'
            %br/
            = link_to '<---Back', rooms_path, class:'button'
        %hr/
        .content