config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rooms do 
  	member do
  		get :new_booking
  		post :create_booking
      get :edit_booking
      post :update_booking
      delete :destroy_booking
  	end

  	resources :fascilities
  end
  resources :holidays
  #get '/:id' => "shortener/shortened_urls#show"

  root to: "pages#index"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :fascilities
  has_many :bookings
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :authenticate_user!


	def index

		condition = []
    condition << "fascilities.name LIKE '%#{params[:query]}%'" if params[:query].present?

    condition = condition.join(' and ')

		@rooms = Room.includes(:fascilities).where(condition).references(:fascilities).order('rooms.created_at desc').page params[:page]
		#@rooms = Room.where("").order(:created_at).page params[:page]
	end

	def show
		@room = Room.find(params[:id])
	end

	def new
		@room = Room.new
	end

	def create
		@room = Room.new(room_params)
		respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, :flash=> {notice: 'Room has been created.' }}
        format.json { render :index, status: :created, location: rooms_path }
      else
        format.html { render :index }
        format.json { render json: @room, status: :unprocessable_entity }
      end
    end
  end

	def edit
		@room = Room.find(params[:id])
	end

	def update
		@room = Room.find(params[:id])
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@room = Room.find(params[:id])
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_path, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
	end

  def new_booking
  	@booking = Booking.new
  	@room_id = params["id"]
  end

  def create_booking
		@user = current_user
		@rooms = Room.where("")
		@booking = Booking.new(booking_params)
		@bookings = Booking.where(:room_id => booking_params[:room_id],:booked_date => booking_params[:booked_date])
		respond_to do |format|
      if @booking.save
      	if @booking[:status].to_i != 0
      		RoomManagementMailer.booking_confirmation_for_waiting(@user,@booking).deliver
      		format.html { redirect_to rooms_path, :flash=> {notice: "Room can't be booked, As this time slot is already booked. You are in Queue, If earlier record get cancelled then you will get the room booking confirmation" }}
      		format.json { render :index, status: :created, location: rooms_path }
      	else
      		RoomManagementMailer.booking_confirmation(@user).deliver
        	format.html { redirect_to rooms_path, :flash=> {notice: 'Room has been booked.' }}
        	format.json { render :index, status: :created, location: rooms_path }
      	end
      else
        format.html { render :new_booking }
        format.json { render json: @booking, status: :unprocessable_entity }
      end
    end
  end

  def edit_booking
  	@booking = Booking.find(params[:id])
  end

  def update_booking
		@booking = Booking.find(params[:id])
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to root_path, notice: 'Booking was successfully updated.' }
        format.json { render :index, status: :ok, location: root_path }
      else
        format.html { render :edit_booking }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_booking
  	@user = current_user
		@booking = Booking.find(params[:id])
    @booking.destroy
    SendMailWorker.perform_async(@booking.booked_date,@booking.end_date,@booking.room_id,@booking.status,@user.id)
    RoomManagementMailer.booking_cancelation(@user).deliver
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def room_params
    params.require(:room).permit(:room_no)
  end

  def booking_params
  	params[:booking][:booked_date] = Time.parse(params[:booking][:booked_date]).strftime '%d/%m/%Y %I:%M %p'
  	date = Time.parse(params[:booking][:booked_date]) + (params[:booking][:duration].to_i * 60)
  	params[:booking][:end_date] = date.strftime '%d/%m/%Y %I:%M %p'

  	st_time_for_query = Time.parse(params[:booking][:booked_date]).strftime '%Y-%m-%d %H:%M:%S'
  	ed_time_for_query = Time.parse(params[:booking][:end_date]).strftime '%Y-%m-%d %H:%M:%S'
  	start_bookings = Booking.where('room_id = ? and booked_date <= ? and end_date >= ?',params[:booking][:room_id],st_time_for_query,st_time_for_query)
    end_bookings = Booking.where('room_id = ? and booked_date <= ? and end_date >= ?',params[:booking][:room_id],ed_time_for_query,ed_time_for_query)
    if start_bookings.present? || end_bookings.present?
    	params[:booking][:status] = 	start_bookings.last.status.to_i + 1
    else
    	params[:booking][:status] = 0
    end
    params.require(:booking).permit(:room_id, :user_id, :booked_date, :duration,:end_date,:status)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.haml
= form_for(@room) do |f|
  .row
    .col-sm-4
      .field.form-group
        .control
          = f.label  :room_no
          = f.text_field :room_no, class: "input form-control"
      .field.form-group
        .control
          = f.submit :submit, class: "button is-link btn btn-info"

app/views/rooms/_form_booking.html.haml
= form_for(@booking, url: update_booking_room_path) do |f|
  - if @booking.errors.any?
    #error_explanation
      %h2
        = pluralize(@booking.errors.count, "error")
        prohibited
        this booking from being saved:
      %ul
        - @booking.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-sm-4
      = f.hidden_field :user_id, value: current_user[:id], class: "input form-control"
      .field.form-group
        .control
          = f.label  :room_id
          = f.select :room_id, options_for_select(Room.all.collect {|p| [ p.room_no, p.id ]}, @booking.room_id), { :prompt => 'Select Room'}, class: "input form-control"
      .field.form-group
        = f.label  "booking date & time"
        #datetimepicker.input-group.date
          = f.text_field :booked_date, class: "input form-control"
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
      .field.form-group
        .control
          = f.label  :duration
          (In Minutes)
          \#{f.text_field :duration, class: "input form-control"}
        /
          <div class="control col-sm-4">
          <haml_silent></haml_silent> (In Minutes)
          <haml_silent>
          </haml_silent><haml_silent>
          </haml_silent>
          </div>
      .field
        .control
          = f.submit :submit, class: "button is-link btn btn-info"
:javascript
  $(function () {
     var date = new Date();
     date.setDate(date.getDate());


     $('#datetimepicker').datetimepicker({
       format: 'DD/MM/YYYY hh:mm A',
       daysOfWeekDisabled: [0, 6]
       //minDate: new Date()
     });
      
     $('#datetimepicker1').datetimepicker({
       format: 'DD/MM/YYYY hh:mm A',
       daysOfWeekDisabled: [0, 6]
       //minDate: new Date()
     });
  });

app/views/rooms/edit.html.haml
.section
  .container
    %h1.title.is-2 Editing Room
    = render 'form', room: @room
    = link_to '<--Back', rooms_path, class:'button btn btn-link'

app/views/rooms/edit_booking.html.haml
.section
  .container
    %h1.title.is-2 Editing Room
    = render 'form_booking', booking: @booking
    = link_to '<--Back', root_path, class:'button btn btn-link'

app/views/rooms/index.html.haml
%p#notice= notice
%h1 Rooms
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Facilities
      %th.text-center{:colspan => "5"} Action
  %tbody
    - @rooms.each do |room|
      %tr
        %td= room.room_no
        %td= room.fascilities.pluck(:name).join(',')
        %td= link_to 'Show', room
        %td= link_to 'Book This Room', new_booking_room_path(room)
        - if can? :new, Fascility
          %td= link_to 'See facility List', room_fascilities_path(room)
        %td= link_to 'Edit', edit_room_path(room)
        %td= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= paginate @rooms, theme: 'my_custom_theme'
%br/
- if can? :new, Room
  = link_to 'Add New Room', new_room_path, class: 'btn btn-primary'

app/views/rooms/new.html.haml
.section
  .container
    %h1.title.is-2 New room
    = render 'form', room: @room
    %br/
    = link_to '<--Back', rooms_path, class:'button btn btn-link'

app/views/rooms/new_booking.html.haml
= form_for(@booking, url: create_booking_room_path) do |f|
  - if @booking.errors.any?
    #error_explanation
      %h2
        = pluralize(@booking.errors.count, "error")
        prohibited
        this booking from being saved:
      %ul
        - @booking.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-sm-4
      = f.hidden_field :user_id, value: current_user[:id], class: "input form-control"
      .field.form-group
        .control
          = f.label  :room_id
          = f.select :room_id, options_for_select(Room.all.collect {|p| [ p.room_no, p.id ]}, @room_id), { :prompt => 'Select Room'}, class: "input form-control"
      .field.form-group
        = f.label  "booking date & time"
        #datetimepicker.input-group.date
          = f.text_field :booked_date, class: "input form-control"
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
      .field.form-group
        .control
          = f.label  :duration
          (In Minutes)
          \#{f.text_field :duration, class: "input form-control"}
          = f.hidden_field :end_date, class: "input form-control"
        /
          <div class="control col-sm-4">
          <haml_silent></haml_silent> (In Minutes)
          <haml_silent>
          </haml_silent><haml_silent>
          </haml_silent>
          </div>
      .field
        .control
          = f.submit :submit, class: "button is-link btn btn-info"
      = link_to '<--Back', rooms_path, class:'button btn btn-link'
:javascript
  $(function () {
     var date = new Date();
     date.setDate(date.getDate());


     $('#datetimepicker').datetimepicker({
       format: 'DD/MM/YYYY hh:mm A',
       daysOfWeekDisabled: [0, 6]
       //minDate: new Date()
     });
      
     $('#datetimepicker1').datetimepicker({
       format: 'DD/MM/YYYY hh:mm A',
       daysOfWeekDisabled: [0, 6]
       //minDate: new Date()
     });
  });

app/views/rooms/show.html.haml
%section.section
  .container
    .columns.is-centered
      .column.is-9
        %h1.title.is-2= @room.room_no
        .level.form-group
          .level-left.control
            %p
              Created on
              \#{@room.created_at} by
              Manager / Modified
              \#{time_ago_in_words(@room.updated_at)}
          .level-left.control
            = link_to 'Edit room', edit_room_path(@room), class:'button'
            = link_to 'Delete room', @room, method: :delete, data: { confirm: 'Are you sure'}, class:'button is-danger is-outlined'
            %br/
            = link_to '<---Back', rooms_path, class:'button'
        %hr/
        .content