config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rooms do 
  	member do
  		get :new_booking
  		post :create_booking
      get :edit_booking
      post :update_booking
      delete :destroy_booking
  	end

  	resources :fascilities
  end
  resources :holidays
  #get '/:id' => "shortener/shortened_urls#show"

  root to: "pages#index"
end

app/models/fascility.rb
class Fascility < ApplicationRecord
  belongs_to :room
end

app/controllers/fascilities_controller.rb
class FascilitiesController < ApplicationController

  before_action :authenticate_user!

	def index
		@room = Room.find(params[:room_id])
		@fascilities = @room.fascilities.where("").order(:created_at).page params[:page]
	end

	def show
		@fascility = Fascility.find(params[:id])
		@room = @fascility.room
	end

	def new
		@room = Room.find(params[:room_id])
		@fascility = @room.fascilities.build
	end

	def create
		@room = Room.find(params[:room_id])
		@fascility = @room.fascilities.new(fascility_params)
		respond_to do |format|
      if @fascility.save
        format.html { redirect_to room_fascilities_path, :flash=> {notice: 'fascility has been created.' }}
        format.json { render :index, status: :created, location: fascilitys_path }
      else
        format.html { render :index }
        format.json { render json: @fascility, status: :unprocessable_entity }
      end
    end
  end

	def edit
		@room = Room.find(params[:room_id])
		@fascility = Fascility.find(params[:id])
	end

	def update
		@fascility = Fascility.find(params[:id])
		@room = @fascility.room
    respond_to do |format|
      if @fascility.update(fascility_params)
        format.html { redirect_to room_fascility_path(@room, @fascility), notice: 'fascility was successfully updated.' }
        format.json { render :show, status: :ok, location: @fascility }
      else
        format.html { render :edit }
        format.json { render json: @fascility.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@fascility = Fascility.find(params[:id])
    @fascility.destroy
    respond_to do |format|
      format.html { redirect_to room_fascilities_path, notice: 'fascility was successfully destroyed.' }
      format.json { head :no_content }
    end
	end

private
  def fascility_params
    params.require(:fascility).permit(:name, :description)
  end
end

app/helpers/fascilities_helper.rb
module FascilitiesHelper
end

app/views/fascilities/_form.html.haml
= form_with(model: [ @room, @fascility.new_record? ? @room.fascilities.build : @fascility ], local: true) do |f|
  .row
    .col-sm-4
      .field.form-group
        .control
          = f.label  :name
          = f.text_field :name, class: "input form-control"
      .field.form-group
        .control
          = f.label  :description
          = f.text_area :description, class: "input form-control"
      .field.form-group
        .control
          = f.submit :submit, class: "button is-link btn btn-info"

app/views/fascilities/edit.html.haml
.section
  .container
    %h1.title.is-2 Editing facility
    = render 'form', room: @room, fascility: @fascility
  = link_to '<--Back', room_fascilities_path, class:'button btn btn-link'

app/views/fascilities/index.html.haml
%p#notice= notice
%h1 Fascilities
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @fascilities.each do |fascility|
      %tr
        %td= fascility.name
        %td= fascility.description
        %td= link_to 'Show', room_fascility_path(@room, fascility)
        %td= link_to 'Edit', edit_room_fascility_path(@room, fascility)
        %td= link_to 'Destroy', room_fascility_path(@room, fascility), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= paginate @fascilities, theme: 'my_custom_theme'
%br/
- if can? :new, Fascility
  = link_to 'New facility', new_room_fascility_path, class: 'btn btn-primary'
%br/
= link_to '<--Back', rooms_path, class:'button btn btn-link'

app/views/fascilities/new.html.haml
.section
  .container
    %h1.title.is-2 New facility
    = render 'form', fascility: @fascility
    %br/
    = link_to '<--Back', room_fascilities_path(@room), class:'button btn btn-link'

app/views/fascilities/show.html.haml
%section.section
  .container
    .columns.is-centered
      .column.is-9
        %h1.title.is-2= @fascility.name
        .level
          .level-left
            %p
              Created on
              \#{@fascility.created_at} by
              Manager / Modified
              \#{time_ago_in_words(@fascility.updated_at)}
          .level-right
            .buttons
              = link_to 'Edit fascility', edit_room_fascility_path(@room, @fascility), class:'button'
              = link_to 'Delete fascility', room_fascility_path(@room, @fascility), method: :delete, data: { confirm: 'Are you sure'}, class:'button is-danger is-outlined'
          = link_to '<--Back', room_fascilities_path, class:'button btn btn-link'
        %hr/
        .content